apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: socialmedia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: socialmedia-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: socialmedia-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: socialmedia-config
              key: NODE_ENV
        - name: MONGODB_CONNECTION
          value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb-service:27017/socialmedia?authSource=admin"
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: socialmedia-secrets
              key: mongodb-username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: socialmedia-secrets
              key: mongodb-password
        - name: JWTKEY
          valueFrom:
            secretKeyRef:
              name: socialmedia-secrets
              key: jwt-key
        volumeMounts:
        - name: uploads-storage
          mountPath: /app/public
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: uploads-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: socialmedia
spec:
  selector:
    app: server
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
